on: [push]

jobs:
  sarif_to_csv:
    runs-on: ubuntu-latest
    name: test sarif to csv
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Convert sarif to csv
        id: sarif-to-csv
        uses: ./
        with:
          input-file: 'test/results.sarif'
          output-file: 'N3_results.csv'
      - name: Upload CSV
        uses: actions/upload-artifact@v2
        with:
          name: csv-results  # This is the name that will be given to the artifact
          path: results.csv  # This is the path to the file you want to upload
        
