on: [push]

jobs:
  sarif_to_csv:
    runs-on: ubuntu-latest
    name: test sarif to csv
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Convert sarif to csv
        id: sarif-to-csv
        uses: ./
        with:
          input-file: 'test/N3.sarif'
          output-file: 'results.csv'
      
      
